---
title: "Exploratory Analysis"
output: html_document
---

## Project title

Shooting for Glory: A Data-Driven Exploration of Clutch Performance in the NBA

### Authors

Isaac Ramirez

### Date

Spring 2024

### Abstract

Our project explores the concept of clutch shooting in the NBA, analyzing the performance of players in high-pressure situations. This question is important because it can provide insights into the mental and physical preparation required for success in critical game moments. To address this question, we will examine the relationship between clutch shooting percentages and other factors such as game experience, shot difficulty, and player consistency.

### Keywords

NBA, Clutch Shooting, Basketball Analytics, Free throw, shot difficulty

### Introduction  

The capacity to perform well under pressure is a highly valued quality in sports. This is also called clutching. Additionally, clutch shooting is the ability to make important shots at game-changing moments. Many shots have transformed many NBA and WNBA games, series, and seasons. This research examines 1996-97 NBA clutch shooting statistics. Physical skill, mental fortitude, and situational awareness are needed for clutch shooting. Players with clutch genes can focus, adapt, and shoot accurately and confidently. The importance of clutch shooting cannot be overstated, as it can swing the momentum of a game and ultimately decide the outcome. Below are the Research questions: How do clutch shooting percentages vary by game experience? How much of an effect does shot difficulty relate to the outcomes of clutch shooting percentages? Do clutch shooters repeat this ability to make clutch shots consistently? These questions may show mental and physical preparedness for high-pressure success. Patterns and trends in the data may affect coaching and player development. Clubs may offer veteran players additional opportunities at important times if they perform well. If clutch shooting and shot difficulty are associated, athletes who can make tough shots under pressure may thrive. We hope to highlight clutch shooting's complex mechanics and basketball impact by addressing these questions.

### Related Work  

Numerous factors impact basketball players' clutch performance, which has been extensively studied. Considerations include teamwork, player experience, and game setting. In stressful situations, players who can stay cool and focused are more likely to succeed, according to research. Analytics like win probability and clutch scoring percentages have identified NBA clutch performers. Beyond points per game and shooting percentages, these measurements show a player's impact. Also studied are clutch shot mechanics and accuracy. Stephen Curry and other players with a longer shot arc are more accurate in crucial situations, according to research. This stresses technical skill in clutch performance and claims that players who can make challenging shots would perform better under pressure. WNBA clutch players like Arike Ogunbowale, Courtney Vandersloot, and Brittney Griner thrive under pressure. Their unique mix of physical skill, mental grit, and situational awareness helps them succeed in vital situations. Basketball clutch performance research illustrates how physical and emotional factors combine to influence success under pressure. Analyzing these factors and measuring clutch performance can help us understand what makes a player clutch and how teams should strategy to win key games. All of my insights from above are laid out in the references of relevant work below. References: https://gamerant.com/nba-2k22-best-wnba-player-each-position-rating-pg-sg-sf-pf-c/ https://en.wikipedia.org/wiki/Alysha_Clark https://www.inpredictable.com/p/about-this-site.html?m=1 https://www.nba.com/news/stats-leaders-who-are-top-clutch-scorers-this-season https://www.inpredictable.com/2015/05/introducing-sharc-shot-arc-analysis.html?m=1

### The Dataset

The Dataset The nba.csv file includes all NBA clutch shot takers since 1996-97. Data from a list of prominent clutch shots (~64,000) contains player IDs, names, clutch free throw attempts, total clutch shots, clutch shooting percentages, and more. Data Source The data was gathered and given by inpredictable, a company that provides insights on many sports, including basketball. Data Gathering Data was acquired manually using basketballreference.com, assuring correctness and dependability. Data on point difference at the 5-minute mark, when clutch time begins, was manually collected using basketballreference.com. The data also contains manually gathered statistics like minutes played, field goals attempted, and free throws taken up until clutch time. Data Collection Goal The study examined clutchness in basketball, specifically late-game free throw shooting in playoffs and the impact of point disparity. Features of the dataset The dataset has 200 observations (players) and 9 characteristics (columns), making it acceptable for analysis. Combining basic data like rebounds with sophisticated metrics like pace or use rate enables a comprehensive analysis of crucial performance. Moral Issues Consider ethical problems and power dynamics when handling this data, such as possible bias in data collecting and processing, and the effect of results on players and teams. The dataset's concentration on clutch time free throw % as the dependent variable may overemphasize one element of clutch performance, omitting other crucial aspects

### Implications

There are many implications that could be affected by my analysis of players that are clutch. For example, Identifying clutch shooting performance markers aids GM team-building decisions. To make the optimal decisions as a gm you need to recruit high-pressure players, developing clutch shooting training programs, and advising on game strategy and player selection. To clarify, a general manager recruits and signs the top players. Players that perform well under pressure are essential to winning late in the games. Data may help GMs evaluate player clutch characteristics and make informed roster changes. This may include signing clutch shooters or free agents with the skills and perseverance to succeed under pressure. This study may affect GM contract talks and player evaluations. Understanding clutch shooting's importance may help GMs negotiate contracts and evaluate players. Teams who can attract key clutch players may have a superior roster and competitive advantage. The NBA and WNBA may adjust team construction and administration according to the findings of my analysis.

### Limitations & Challenges
The findings of "Shooting for Glory: A Data-Driven Exploration of Clutch Performance in the NBA," must overcome numerous challenges to be reliable. Three important concerns need significant consideration. First Challenge: Data Limits Although vast, the dataset may not capture all clutch shooting instances. It emphasizes playoff late-game free throw shooting, which may not reflect other crucial moments. The dataset may not contain important regular-season or non-playoff shots. This restricted view may not explain clutch performance since players act differently in different games. Shot selection, defense, and collaboration may be overlooked in the dataset's crunch time free throw % concentration. No one statistic can measure clutch performance. The study solely examined free throw %, which may have missed clutch shooting nuances. Problem 2: Methodology To compare clutch shooting percentages to other criteria, use statistical models. These models may not accurately represent clutch performance due to team chemistry, coaching, and player psychology. Clutch performance may rely on teammates, coach, and mental preparation. Intangibles may lead statistical models to oversimplify variable relationships. Statistical models may overemphasize quantitative measures, concealing qualitative findings. Intangible traits that set great athletes apart also impact clutch success. Over-statistical modeling may impede clutch performance studies from comprehending humans. 3. Interpretation Issues This study is interpretable, and "clutch" is subjective. What is a clutch situation, and how do we account for player anxiety in various games? Are playoff game-tying shots more crucial than regular-season game-winning shots? Compare clutch performances from different times, teams, and systems. Data collection and analysis biases may impact research results. Data from playoff games may overrepresent postseason performers, biasing clutch performance. The study must consider these biases and interpret findings nuancedly. Addressing these issues will assure the findings' reliability and provide NBA organizations and players useful data. By acknowledging dataset restrictions, clutch performance difficulty, and interpretation challenges, NBA clutch shooting research may improve.

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
